### ISSUE TITLE
Move loading of Material Icons font

### ISSUE THREAD

**Issue by lcsrinaldi** [picter/prisma#10]
Currently we are loading the Material Icon font like this: 

```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
``` 

@noxan mentioned that we should load it like our other fonts, through a font-face declaration.

**Comment by noxan** [comment]
Sorry, I rather thought of having this font loaded automatically like the others. I was not concerned by the hosting or related things. Sorry for being unclear.

**Comment by lcsrinaldi** [comment]
@noxan , yes, but I think Google doesn't provide us to a URL to load it like the others (through `@font-face`). So I don't know how to proceed with this.

**Comment by noxan** [comment]
We could extract the urls, etc from the file itself, just open https://fonts.googleapis.com/icon?family=Material+Icons

I would prefer to just do an css import and keep google's definitions. But guess @gneutzling mentioned in dev meeting that it could cause issues with nextjs. Otherwise we could just host the files ourselves like we do with other fonts. They can be easily downloaded from https://github.com/google/material-design-icons/tree/master/iconfont

But not high priority, would just be great to avoid importing this font manually in each project.
